data = [
    {
        "name": "Ariana Grande",
        "follower_count": 185,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Barack Obama",
        "follower_count": 140,
        "description": "Former President of the United States",
        "country": "United States",
    },
    {
        "name": "BTS",
        "follower_count": 67,
        "description": "K-pop group",
        "country": "South Korea",
    },
    {
        "name": "Bill Gates",
        "follower_count": 54,
        "description": "Co-founder of Microsoft",
        "country": "United States",
    },
    {
        "name": "Camila Cabello",
        "follower_count": 49,
        "description": "Musician",
        "country": "Cuba",
    },
    {
        "name": "Cardi B",
        "follower_count": 92,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Chris Brown",
        "follower_count": 104,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 340,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "David Beckham",
        "follower_count": 123,
        "description": "Footballer",
        "country": "United Kingdom",
    },
    {
        "name": "Drake",
        "follower_count": 165,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Dua Lipa",
        "follower_count": 67,
        "description": "Musician",
        "country": "United Kingdom",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 182,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Ellen DeGeneres",
        "follower_count": 88,
        "description": "Comedian and TV host",
        "country": "United States",
    },
    {
        "name": "Elon Musk",
        "follower_count": 90,
        "description": "Entrepreneur and CEO of SpaceX and Tesla",
        "country": "United States",
    },
    {
        "name": "Emma Watson",
        "follower_count": 59,
        "description": "Actress",
        "country": "United Kingdom",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 85,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Gigi Hadid",
        "follower_count": 55,
        "description": "Model",
        "country": "United States",
    },
    {
        "name": "Gordon Ramsay",
        "follower_count": 15,
        "description": "Chef and TV personality",
        "country": "United Kingdom",
    },
    {
        "name": "Greta Thunberg",
        "follower_count": 15,
        "description": "Climate activist",
        "country": "Sweden",
    },
    {
        "name": "Instagram",
        "follower_count": 346,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Jack Ma",
        "follower_count": 30,
        "description": "Co-founder of Alibaba",
        "country": "China",
    },
    {
        "name": "Jeff Bezos",
        "follower_count": 10,
        "description": "CEO of Amazon",
        "country": "United States",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 129,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 148,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Justin Timberlake",
        "follower_count": 59,
        "description": "Musician and actor",
        "country": "United States",
    },
    {
        "name": "Kanye West",
        "follower_count": 71,
        "description": "Musician and fashion designer",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 117,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Khloé Kardashian",
        "follower_count": 115,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 170,
        "description": "Reality TV personality and businesswoman",
        "country": "United States",
    },
    {
        "name": "Kourtney Kardashian",
        "follower_count": 93,
        "description": "Reality TV personality",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 175,
        "description": "Reality TV personality and businesswoman and Self-Made Billionaire",
        "country": "United States",
    },
    {
        "name": "Lady Gaga",
        "follower_count": 83,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Larry Page",
        "follower_count": 20,
        "description": "Co-founder of Google",
        "country": "United States",
    },
    {
        "name": "LeBron James",
        "follower_count": 63,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Leonardo DiCaprio",
        "follower_count": 46,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Lewis Hamilton",
        "follower_count": 27,
        "description": "Formula One driver",
        "country": "United Kingdom",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 183,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Mark Zuckerberg",
        "follower_count": 75,
        "description": "CEO of Facebook",
        "country": "United States",
    },
    {
        "name": "Megan Thee Stallion",
        "follower_count": 25,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 113,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Michelle Obama",
        "follower_count": 53,
        "description": "Former First Lady of the United States",
        "country": "United States",
    },
    {
        "name": "Narendra Modi",
        "follower_count": 78,
        "description": "Prime Minister of India",
        "country": "India",
    },
    {
        "name": "NASA",
        "follower_count": 56,
        "description": "Space agency",
        "country": "United States",
    },
    {
        "name": "National Geographic",
        "follower_count": 135,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "name": "NBA",
        "follower_count": 47,
        "description": "Club Basketball Competition",
        "country": "United States",
    },
    {
        "name": "Neymar",
        "follower_count": 141,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 137,
        "description": "Musician",
        "country": "Trinidad and Tobago",
    },
    {
        "name": "Nike",
        "follower_count": 109,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "name": "Oprah Winfrey",
        "follower_count": 42,
        "description": "TV host and philanthropist",
        "country": "United States",
    },
    {
        "name": "Pele",
        "follower_count": 25,
        "description": "Football legend",
        "country": "Brazil",
    },
    {
        "name": "PewDiePie",
        "follower_count": 109,
        "description": "YouTuber",
        "country": "Sweden",
    },
    {
        "name": "Real Madrid CF",
        "follower_count": 86,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Roger Federer",
        "follower_count": 50,
        "description": "Tennis player",
        "country": "Switzerland",
    },
    {
        "name": "Rihanna",
        "follower_count": 102,
        "description": "Musician and businesswoman",
        "country": "Barbados",
    },
    {
        "name": "Satya Nadella",
        "follower_count": 15,
        "description": "CEO of Microsoft",
        "country": "United States",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 175,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Serena Williams",
        "follower_count": 45,
        "description": "Tennis player",
        "country": "United States",
    },
    {
        "name": "Sergey Brin",
        "follower_count": 20,
        "description": "Co-founder of Google",
        "country": "United States",
    },
    {
        "name": "Shakira",
        "follower_count": 68,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Shawn Mendes",
        "follower_count": 57,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Stephen Curry",
        "follower_count": 31,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Sundar Pichai",
        "follower_count": 25,
        "description": "CEO of Google",
        "country": "United States",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 132,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "The Rock",
        "follower_count": 119,
        "description": "Actor and wrestler",
        "country": "United States",
    },
    {
        "name": "Tim Cook",
        "follower_count": 20,
        "description": "CEO of Apple",
        "country": "United States",
    },
    {
        "name": "Tom Brady",
        "follower_count": 15,
        "description": "American football player",
        "country": "United States",
    },
    {
        "name": "UEFA Champions League",
        "follower_count": 58,
        "description": "Club football competition",
        "country": "Europe",
    },
    {
        "name": "Usain Bolt",
        "follower_count": 25,
        "description": "Sprinter",
        "country": "Jamaica",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 168,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Will Smith",
        "follower_count": 115,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 69,
        "description": "Actress and musician",
        "country": "United States",
    },
]
